name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
            python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-rtd-dropdown
      - name: Build docs
        run: |
          mkdocs build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: site # The folder the action should deploy.
            CLEAN: true # Automatically remove deleted files from the deploy branch
